# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 899c2eda433502d663ce8cc44280e54fa441012804a101bd6434bf1e4f1286880b1d173b11edbcf6d0a25cd7d136d29e5b31a70d38837aea49da9647eb98fb72

test:
  secret_key_base: cb5b306a2c5178c92b8e36705572fc6d2d3742e542ddba5aa91597bb897e9240ad515c7b3b93526ea9d92c87a074d8b52a8e025d19e7da37786bc0de926f4ad3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
